### ISSUE TITLE
Redirect to /moderation

### ISSUE THREAD

**Issue by alefunt** [Glorious-Screwdriver/webapp-audiostock#46]
ему не доступны фавориты и корзина но он на главном
а наверное он модер
тогда хорошо бы ему отдельный view

**Comment by clif2501** [comment]
Он модер, просто ему ранее были назначены треки, поэтому они отображаются как обычно. Сделаю редирект с любой страницы на `/moderation`, не подумал об этом почему-то.
А вообще `ModeratorController` уже есть
