### ISSUE TITLE
Банковские операции

### ISSUE THREAD

**Issue by alefunt** [Glorious-Screwdriver/webapp-audiostock#49]
Нужно решить как их реализовать и сделать это.

**Comment by alefunt** [comment]
Вроде как можно оформить на стороне клиента проверку карты на действительность

**Comment by alefunt** [comment]
хотя наверное это не круто

**Comment by clif2501** [comment]
Я думал бы не будем так глубоко копать. Чтобы нормально проверять карты и работать с ними надо подключать банковских провайдеров и заключать с ними контракты😁 Поэтому мне кажется, что надо ограничиться просто заносом данных в бд и проверкой на заполнение всех полей

**Comment by alefunt** [comment]
справедливо, но подумать стоит
